name: inception

services:
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      args:
        - WORDPRESS_DATABASE
        - WORDPRESS_USER
        - WORDPRESS_PASSWORD
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      args:
        - WORDPRESS_DATABASE
        - WORDPRESS_USER
        - WORDPRESS_PASSWORD
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: /home/acesar-l/data/mariadb
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/acesar-l/data/wordpress
